### ISSUE TITLE
where is the api  to get x-ebay-signature-key

### ISSUE THREAD

**Issue by ex-melody** [eBay/digital-signature-verification-ebay-api#2]
https://developer.ebay.com/develop/guides/digital-signatures-for-apis  
Developers will be issued a private key, as well as a public key in the form of a JWE. The keys can be downloaded through an eBay public API. In the meantime, we have provided test keys below.
what is this public api.
where is  an eBay public API to downloaded the keys.

and how to build a signature_base?
is this signatureBase ok?
"content-digest": sha256=:qHHEen9IoSs4qZTkipZZ+rXWN289vON1Wby2F+/oZi0=:
"x-ebay-signature-key": testPublicKey
"@method": POST
"@path": /verifysignature
"@authority": 127.0.0.1
"@signature-params": ("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1660611465471;alg="rsa-v1_5-sha256"

**Comment by notqualia** [comment]
for me,when i replace 'Ed25519 public key(as JWE)' with 'RSA public key(as JWE)'
```
curl --location --request POST 'http://localhost:8085/verifysignature' \
--header 'Content-Type: application/json' \
--header 'Signature-Input: sig1=("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1658440308' \
--header 'Content-Digest: sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:' \
--header 'Signature: sig1=:uunxYrXKC8KaoupD5D1DKdmQmrOhz6b4Xbhb3o9d4x4xFIpg++XzEZztOyeOI59rMMjM3NIcFgxBH0c1ckpfBw==:' \
--header 'x-ebay-signature-key: eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoiQlh3VVljQ1MyRHBEeW4xanNrSUVrQSIsImFsZyI6IkEyNTZHQ01LVyIsIml2IjoiSFlKZV9pX1JvX3dEVFRjeSJ9.mzzNmEYVENteXFyYGwOuIjDcRDBsMrEm_g43Lv7-oWU.-XI55qpQSn1SKgE8.bIFK9LmDVbo119VibK9dAHhRIzXs58HfyJMCoc9bwU6WEZlRo7E_PwPge3npGP9a4IcQH1VD4uO7_J0XbJvv9IaakVMJ4D8Hzh9dBetuwkY3zZ00ObE9KcVNA4iHdalQ4jYkZboabWTtQDqQjIf19sgbBwXAEoLkHruJAbdPWflqfqQ4VTeP3Az6Q9wDhEKAWLNyKWIbN8DCTPlTJa_DzJDwvQhyYVDqD0rg8fnaq4KAXFGrk-l2ztbEQEkylzqTrRu-6g_5WGdihfL9YG2jtdmU3YJwr46SLDJvc4RixzUsf2URbxoWvKDGEGit4h1vnBykeXA3jp90Kk7aAa-7h6ZLi1ajMWAG65ph6lZUeXqLdKeHR-NCuonOrI9_cjFbhVn7AY1Slq0jxrA7Ws2QL4LRulo6RZVe21IaicoDEpa6RtNAg9FDzQfNa2ke16c4RGOI0cWxsvfX8fygzRyQM7N-ODC0Gkm5Ip4ikmdJEY8ovN3LSPXCMdWxqVAw9X_LMFjo1X2_XCycigKXnrZrBA7L3-czGXUq8SWfuqm_RLN4.VE2ryVxII2YFuD65f35opg' \
--data-raw '{"hello": "world"}'
```
it return error
Error parsing JWE from x-ebay-signature-key header: encoded key spec not recognized: algorithm identifier 1.2.840.113549.1.1.1 in key not recognized

**Comment by uherberg** [comment]
@ex-melody The API isn't available yet, but will be on October 1. We will send out an announcement once it is available. You can test your code in the meantime using the test keys that we provide and using the code I implemented.
You can read in the IETF draft how to build the signature base: https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures#section-2.4
Let me know if that answers your question
