### ISSUE TITLE
After signing, the request error 215120 occurred and various methods have been tried without effect.

### ISSUE THREAD

**Issue by ajinle** [eBay/digital-signature-verification-ebay-api#21]
Hello, I followed the relevant requirements of the document and used the RSA signature method to sign, but the request reported an error：
{ "errors": [ { "errorId": 215120, "domain": "ACCESS", "category": "REQUEST", "message": "Signature validation failed", "longMessage": "Signature validation failed to fulfill the request." } ] }

Since we are using C# technology here, I found that there is no relevant SDK, so I can only write my code through the requirements of the document and the SDK of other languages. According to the requirements of the document, I used RSA with SHA256 hash algorithm and Pkcs1 padding mode to sign. The local signature and verification are correct, but the interface still responds with “errorId”: 215120

This is what it looks like before signing：
"x-ebay-signature-key":eyJ6aXAiOiJERUYiLCJraWQiOiJiNmI4....
"@method":GET
"@path":/sell/finances/v1/payout
"@authority":apiz.ebay.com
"@signature-params":("x-ebay-signature-key" "@method" "@path" "@authority");created=1683883448

The result after signing with privateKey：
NqJjlEbDcpBBwb6PK+LczubQXn1/JeBQRkl7UhER5seDtDbTfNsjsc/kdvUfRwJHBQihnnFu6voKb3lwQ4al3AXl8/lB/SziB9XWlOwVFD/Irk3tiJhrRTKRZbrxL6k0Z5Z/LnuYdQguwusVK+hPMfgroWF4bmoX5jRd00xTet29d+oWl3HMjczeqYyR+Y2bmlUAtdIbYhM0xKlIg1Cj6R5/jlKzDnxWCQau7YcVOtJnMV9xqJkPfsI8MuuJkb8bJlqIOsXCKgcntNp0LjRBVud990LM2MxhE4tkhoAtybwq1TerInIfPtmAEamXwlNbuqqJ4CWo/KOJauZTXObJbg==

The content of the request and the result of the response：
![image](https://github.com/eBay/digital-signature-verification-ebay-api/assets/131935169/d63432ae-fba3-4819-947d-247513d9c1b6)

Thanks.

**Comment by uherberg** [comment]
@ajinle : This may be just a typo here on the above sniplet of the signature base, but it looks like there is no space after the colon. For example, it should be `"@method": GET` not `"@method":GET`. Can you check if that's how you create the signature base?

**Comment by ajinle** [comment]
> @ajinle: 这可能只是上述签名基础片段中的一个错字，但看起来冒号后面没有空格。例如，它`"@method": GET`不应该`"@method":GET`。你能检查一下你是不是这样创建签名库的吗？

OK, I just tried it and it worked, thanks

**Comment by ajinle** [comment]
I have another question here, is the signed key applied for only related to the developer? Because I found that the binding is the same when obtaining the signing key through the store under the developer

**Comment by uherberg** [comment]
@ajinle The downloaded key is bound per app. Most developers only have one app, but it is possible to request more than one app. In that case, a developer may have several keys one for each app.

**Comment by ajinle** [comment]
> @ajinle下载的密钥是每个应用程序绑定的。大多数开发人员只有一个应用程序，但可以请求多个应用程序。在这种情况下，开发人员可能有多个密钥，每个应用程序一个。

ok thank you very much for your answer
