### ISSUE TITLE
Hardcoded algorithm value in KeyPairService

### ISSUE THREAD

**Issue by jsaxdev** [eBay/digital-signature-verification-ebay-api#5]
There is hardcoded algorithm value in KeyPairService class which is always "_**Ed25519**_". So your service cannot verify JWT when JWE value algorithm is RSA.

**Comment by uherberg** [comment]
@jsaxdev Good point. This [PR](https://github.com/eBay/digital-signature-verification-ebay-api/pull/6), once merged, should address this. The variable is still there, but this only affects the signature creation. Verification will support both algorithms, depending on what the JWE from the request inclues.

**Comment by uherberg** [comment]
@jsaxdev The PR has been merged. Please give it a try and let me know if this works better
